use anyhow::Result;
use rusqlite::Connection;

pub fn create_tables(conn: &Connection) -> Result<()> {
    conn.execute_batch(
        "
        PRAGMA journal_mode=WAL;

        -- journal_mode is persistent per-database, but these two are
        -- per-connection and must be set on every connection that is opened.
        -- busy_timeout is not optional: /api/evaluate writes evidence rows, so
        -- there is more than one writer, and without it a concurrent write
        -- surfaces as SQLITE_BUSY -> HTTP 500 rather than a short wait.
        PRAGMA busy_timeout=5000;
        PRAGMA synchronous=NORMAL;

        -- Every country that exists, independent of whether it has been
        -- researched. Deliberately separate from `countries`, which holds the
        -- small set of hand-researched policy dossiers and whose columns are
        -- all NOT NULL: widening that table to the whole world would mean
        -- making sanctions_tier nullable, which every consumer in engine/
        -- reads unconditionally.
        --
        -- `include_on_globe` is derived from whether the basemap actually has
        -- geometry for the country, so the set of drawable countries is a
        -- query rather than a hardcoded array. Generated by
        -- scripts/gen_country_reference.mjs.
        CREATE TABLE IF NOT EXISTS country_reference (
            country_code     TEXT PRIMARY KEY,
            country_name     TEXT NOT NULL,
            alpha3           TEXT,
            iso_numeric      TEXT,
            region           TEXT,
            subregion        TEXT,
            centroid_lat     REAL,
            centroid_lon     REAL,
            bbox_min_lon     REAL,
            bbox_min_lat     REAL,
            bbox_max_lon     REAL,
            bbox_max_lat     REAL,
            include_on_globe INTEGER NOT NULL DEFAULT 1,
            priority_tier    INTEGER NOT NULL DEFAULT 100
        );

        CREATE TABLE IF NOT EXISTS countries (
            country_code             TEXT PRIMARY KEY,
            country_name             TEXT NOT NULL,
            sanctions_tier           TEXT NOT NULL,
            us_service_access        TEXT NOT NULL,
            cloud_access_notes       TEXT NOT NULL,
            export_control_notes     TEXT NOT NULL,
            last_major_legal_change  TEXT,
            compute_capacity_band    TEXT NOT NULL,
            confidence               TEXT NOT NULL,
            source_notes             TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS model_releases (
            model_id              TEXT PRIMARY KEY,
            provider              TEXT NOT NULL,
            model_name            TEXT NOT NULL,
            origin_country        TEXT NOT NULL,
            release_date          TEXT NOT NULL,
            weight_access         TEXT NOT NULL,
            license_type          TEXT NOT NULL,
            parameter_class       TEXT NOT NULL,
            local_deployability   TEXT NOT NULL,
            telemetry_risk_default TEXT NOT NULL,
            confidence            TEXT NOT NULL,
            huggingface_repo_id   TEXT,
            source_notes          TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS model_usage (
            model_id            TEXT PRIMARY KEY,
            downloads_all_time  INTEGER NOT NULL,
            checked_date        TEXT NOT NULL,
            source_notes        TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS adoption_signals (
            signal_id        TEXT PRIMARY KEY,
            country_code     TEXT NOT NULL,
            provider         TEXT NOT NULL,
            model_or_service TEXT NOT NULL,
            user_segment     TEXT NOT NULL,
            signal_type      TEXT NOT NULL,
            value_text       TEXT NOT NULL,
            signal_date      TEXT NOT NULL,
            confidence       TEXT NOT NULL,
            source_notes     TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS technology_blocks (
            country_code      TEXT NOT NULL,
            category          TEXT NOT NULL,
            technology        TEXT NOT NULL,
            domain_or_url     TEXT NOT NULL,
            test_name         TEXT NOT NULL,
            status            TEXT NOT NULL,
            anomaly_rate      REAL NOT NULL,
            measurement_count INTEGER NOT NULL,
            checked_date      TEXT NOT NULL,
            source_notes      TEXT NOT NULL,
            PRIMARY KEY (country_code, technology)
        );

        CREATE TABLE IF NOT EXISTS blocking_timeline (
            country_code      TEXT NOT NULL,
            technology        TEXT NOT NULL,
            measurement_date  TEXT NOT NULL,
            anomaly_count     INTEGER NOT NULL,
            confirmed_count   INTEGER NOT NULL,
            measurement_count INTEGER NOT NULL,
            ok_count          INTEGER NOT NULL,
            PRIMARY KEY (country_code, technology, measurement_date)
        );

        -- Per-transport columns are additive and nullable: Tor's combined CSV
        -- lags the per-country one by a day or two, so a row can legitimately
        -- have bridge_users but no transport split yet. Any change to the
        -- columns below must also be added to db/migrations.rs — this block
        -- only ever runs against a database that does not exist yet.
        CREATE TABLE IF NOT EXISTS tor_metrics (
            id TEXT PRIMARY KEY,
            country_code TEXT NOT NULL,
            date TEXT NOT NULL,
            relay_users INTEGER,
            bridge_users INTEGER,
            bridge_relay_ratio REAL,
            blocking_signal TEXT,
            source TEXT DEFAULT 'TOR_METRICS',
            obfs4_low INTEGER,
            obfs4_high INTEGER,
            snowflake_low INTEGER,
            snowflake_high INTEGER,
            webtunnel_low INTEGER,
            webtunnel_high INTEGER
        );

        CREATE TABLE IF NOT EXISTS country_scores (
            id TEXT PRIMARY KEY,
            country_code TEXT NOT NULL,
            source TEXT NOT NULL,
            year INTEGER NOT NULL,
            score_overall REAL,
            score_access REAL,
            score_content REAL,
            score_rights REAL,
            classification TEXT,
            last_updated TEXT
        );

        CREATE TABLE IF NOT EXISTS services (
            service_id TEXT PRIMARY KEY,
            service_name TEXT NOT NULL,
            category TEXT NOT NULL,
            provider TEXT,
            stack_role TEXT NOT NULL,
            notes TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS service_channels (
            channel_id TEXT PRIMARY KEY,
            service_id TEXT NOT NULL,
            channel_type TEXT NOT NULL,
            channel_name TEXT NOT NULL,
            internet_required BOOLEAN NOT NULL,
            foreign_operator_risk TEXT,
            notes TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS path_templates (
            path_id TEXT PRIMARY KEY,
            label TEXT NOT NULL,
            architecture_family TEXT NOT NULL,
            description TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS path_dependencies (
            path_id TEXT NOT NULL,
            dependency_type TEXT NOT NULL,
            dependency_target TEXT NOT NULL,
            required BOOLEAN NOT NULL,
            notes TEXT,
            PRIMARY KEY (path_id, dependency_type, dependency_target)
        );

        CREATE TABLE IF NOT EXISTS country_constraints (
            constraint_id TEXT PRIMARY KEY,
            country_code TEXT NOT NULL,
            target_type TEXT NOT NULL,
            target_id TEXT NOT NULL,
            constraint_type TEXT NOT NULL,
            status TEXT NOT NULL,
            summary TEXT NOT NULL,
            applies_to_org_type TEXT,
            applies_to_sensitivity TEXT,
            confidence TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS evidence_items (
            evidence_id TEXT PRIMARY KEY,
            source_type TEXT NOT NULL,
            title TEXT NOT NULL,
            publisher TEXT,
            url TEXT,
            observed_at TEXT,
            claim_text TEXT NOT NULL,
            confidence TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS constraint_evidence (
            constraint_id TEXT NOT NULL,
            evidence_id TEXT NOT NULL,
            PRIMARY KEY (constraint_id, evidence_id)
        );

        CREATE TABLE IF NOT EXISTS path_evidence (
            path_id TEXT NOT NULL,
            evidence_id TEXT NOT NULL,
            PRIMARY KEY (path_id, evidence_id)
        );

        -- Country-level internet outage/shutdown events from IODA (Georgia
        -- Tech / CAIDA). Each row is one detected outage window for one
        -- country as seen by one datasource (bgp / ping-slash24 / merit-nt /
        -- gtr). `end_ts` is stored (= start_ts + duration_secs) so 'currently
        -- degraded' is a plain range query rather than an expression the
        -- planner can't index. `score` is IODA's severity magnitude.
        CREATE TABLE IF NOT EXISTS outage_events (
            id            TEXT PRIMARY KEY,
            country_code  TEXT NOT NULL,
            start_ts      INTEGER NOT NULL,
            duration_secs INTEGER NOT NULL,
            end_ts        INTEGER NOT NULL,
            datasource    TEXT NOT NULL,
            method        TEXT,
            score         REAL NOT NULL,
            source        TEXT NOT NULL,
            last_updated  TEXT NOT NULL
        );

        -- Per-content-category censorship for a country, from OONI's
        -- aggregation API grouped by Citizen Lab category_code (NEWS, HUMR,
        -- LGBT, POLR, ...). One row per (country, category): the share of
        -- web_connectivity measurements in that category that came back
        -- anomalous, with the confirmed-blocked count as corroboration. This is
        -- the per-category (what kinds of content are censored) view.
        CREATE TABLE IF NOT EXISTS category_blocks (
            country_code      TEXT NOT NULL,
            category_code     TEXT NOT NULL,
            category_label    TEXT NOT NULL,
            status            TEXT NOT NULL,
            anomaly_rate      REAL NOT NULL,
            anomaly_count     INTEGER NOT NULL,
            confirmed_count   INTEGER NOT NULL,
            measurement_count INTEGER NOT NULL,
            checked_date      TEXT NOT NULL,
            source_notes      TEXT NOT NULL,
            PRIMARY KEY (country_code, category_code)
        );

        -- ── Indexes ──────────────────────────────────────────────────────
        --
        -- tor_metrics is keyed on a synthetic `id` ('{country}-{date}'), so
        -- the only query that matters ('WHERE country_code = ? ORDER BY date')
        -- had no usable index and planned as a full SCAN plus a temp B-tree
        -- sort. Invisible at a few thousand rows; a full scan and sort of the
        -- whole table on every sidebar open once this covers every country.
        CREATE INDEX IF NOT EXISTS idx_tor_metrics_country_date
            ON tor_metrics(country_code, date);

        -- technology_blocks' PRIMARY KEY (country_code, technology) already
        -- serves lookups by country via prefix, but /api/blocking also filters
        -- on category alone.
        CREATE INDEX IF NOT EXISTS idx_tech_blocks_category
            ON technology_blocks(category);

        CREATE INDEX IF NOT EXISTS idx_adoption_signals_country
            ON adoption_signals(country_code);

        CREATE INDEX IF NOT EXISTS idx_country_scores_country_year
            ON country_scores(country_code, year DESC);

        -- outage_events is read two ways: per-country history ('WHERE
        -- country_code = ? ORDER BY start_ts') for the sidebar timeline, and
        -- 'recently active across all countries' ('WHERE end_ts >= ?') for the
        -- globe overlay/feed. One composite serves the first; a dedicated
        -- end_ts index serves the second once this covers every country.
        CREATE INDEX IF NOT EXISTS idx_outage_events_country_start
            ON outage_events(country_code, start_ts DESC);
        CREATE INDEX IF NOT EXISTS idx_outage_events_end
            ON outage_events(end_ts DESC);

        -- blocking_timeline deliberately gets nothing: its PRIMARY KEY
        -- (country_code, technology, measurement_date) autoindex already
        -- serves every current query and supplies their ORDER BY for free.
        -- Any index added here is paid on every row of a ~600k-row sweep.
    ",
    )?;
    Ok(())
}
